[package]
name = "interpreter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

sha2 = "0.10.6"
sha256 = "1.0.3"
ripemd = "0.1.3"
sha-1 = "0.10.0"
